# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gyL9PPuW3g5sSZhnTsbBMLgHUFQrzQ1M
"""

d# O Algoritmo de Auditoria de Dados

LIMITE_SEGURANCA = 10000.00

# Função
def analisar_vendas(venda1, venda2, venda3):
    global LIMITE_SEGURANCA

    # Apresentando os tipos de dados apos o casting
    print("TIPOS DE DADOS APOS O CASTING:")
    print("venda1 = " + str(venda1) + " | tipo: " + str(type(venda1)))
    print("venda2 = " + str(venda2) + " | tipo: " + str(type(venda2)))
    print("venda3 = " + str(venda3) + " | tipo: " + str(type(venda3)))

    # Calculo da media
    soma = venda1 + venda2 + venda3
    media = soma / 3
    print("\nSoma das vendas: R$ " + str(soma))
    print("Media das vendas: R$ " + str(media))
    print("Limite de seguranca atual: R$ " + str(LIMITE_SEGURANCA))

    # Verifica se a media ultrapassa o limite de segurança
    if media > LIMITE_SEGURANCA:
        print("\nALERTA: SISTEMA EM QUARENTENA")
        resposta = input(" Deseja atualizar o LIMITE_SEGURANCA? (s/n): ")
        if resposta == "s":
            novo_limite = float(input("Digite o novo limite: "))
            LIMITE_SEGURANCA = novo_limite
            print("Limite atualizado para: R$ " + str(LIMITE_SEGURANCA))
    else:
        print("\nDentro do limite de seguranca.")

    # Verificação
    if venda1 >= media * 5:
        print("\nREVISAO MANUAL SUGERIDA")
        print("Venda 1 e 5x maior que a media.")
    if venda2 >= media * 5:
        print("\nREVISAO MANUAL SUGERIDA")
        print("Venda 2 e 5x maior que a media.")
    if venda3 >= media * 5:
        print("\nREVISAO MANUAL SUGERIDA")
        print("Venda 3 e 5x maior que a media.")

# ENTRADA DE DADOS
venda1 = float(input("Digite o valor da Venda 1: "))
venda2 = float(input("Digite o valor da Venda 2: "))
venda3 = float(input("Digite o valor da Venda 3: "))

# EXECUCAO
analisar_vendas(venda1, venda2, venda3)
print("\nFIM ")